CREATE TABLE Artists (
artID INT NOT NULL AUTO_INCREMENT,
artName VARCHAR(255) NOT NULL,
CONSTRAINT pk_artists PRIMARY KEY (artID),
CONSTRAINT ck_artists UNIQUE (artName)
);

CREATE TABLE Albums (
artID INT NOT NULL,
albumID INT NOT NULL AUTO_INCREMENT,
albumGenre VARCHAR(63) NULL,
albumTitle VARCHAR(255) NOT NULL,
albumPrice FLOAT(5,2) NULL,
albumNumOfTracks INT NULL,
CONSTRAINT pk_albums PRIMARY KEY (albumID)
);

ALTER TABLE Albums ADD CONSTRAINT fk_albums_art FOREIGN KEY (artID)
REFERENCES Artists (artID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE Tracks (
albumID INT NOT NULL, 
trackID INT NOT NULL AUTO_INCREMENT,
trackTitle VARCHAR(255) NOT NULL,
trackRunningTime INT NULL,
CONSTRAINT pk_tracks PRIMARY KEY (trackID)
);

ALTER TABLE Tracks ADD CONSTRAINT fk_tracks_alb FOREIGN KEY (albumID)
REFERENCES Albums (albumID) ON DELETE CASCADE ON UPDATE CASCADE;